version: '3.9'

"""
PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
PROJECT_NUM=$(gcloud projects describe ${PROJECT_ID} --format="value(projectNumber)" 2>/dev/null)
TEST_IMAGE_BASE_NAME="us-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO_NAME}/${ARTIFACT_PKG_NAME}"
TEST_IMAGE_TAG=$(gcloud artifacts tags list \
    --package=${ARTIFACT_PKG_NAME} \
    --location=us \
    --repository=${ARTIFACT_REPO_NAME} \
    --project ${PROJECT_ID} \
    2>&1 | grep -Eo '^[0-9]+' | sort -n | tail -n 1)
TEST_IMAGE_NAME="${TEST_IMAGE_BASE_NAME}:${TEST_IMAGE_TAG}"
export PROJECT_ID PROJECT_NUM TEST_IMAGE_NAME
"""

services:
  main-service:
    image: "${TEST_IMAGE_NAME}"
    entrypoint: poetry
    command: run bash
    ports:
      - "5001:5001"
    environment:
      IN_DEV: "True"
      IN_PROD: "False"
      GOOGLE_CLOUD_PROJECT: "${PROJECT_ID}"
      PROJECT_ID: "${PROJECT_ID}"
      PROJECT_NUM: "${PROJECT_NUM}"
    volumes:
      - ./main_service:/home/pkg_dev/app
      - ~/.config/gcloud:/home/pkg_dev/.config/gcloud
    working_dir: /home/pkg_dev/app