import os
from burla import remote_parallel_map

huggingface_token = os.environ["HUGGINGFACE_TOKEN"]
worker_cache = {}


def do_inference(prompt: str):
    from vllm import LLM, SamplingParams
    from huggingface_hub import login

    if not worker_cache.get("llm"):
        login(huggingface_token)
        model_name = "meta-llama/Meta-Llama-3-8B-Instruct"
        worker_cache["llm"] = LLM(model=model_name, dtype="float16", tensor_parallel_size=1)

    sampling_params = SamplingParams(temperature=0.7, top_p=0.95)
    output = worker_cache["llm"].generate(prompt, sampling_params)
    response = output[0].outputs[0].text
    print(f"\nQuestion: {prompt}\nResponse: {response}")
    return response


prompts = [
    "Write a short motivational quote.",
    "Summarize the plot of a famous novel.",
    "Define artificial intelligence in one sentence.",
    "Explain quantum computing simply.",
    "Write a funny tweet about coffee.",
    "Generate a tagline for a gym.",
    "Describe a peaceful beach scene.",
    "Explain how a car engine works.",
    "Write a haiku about winter.",
    "Suggest a dinner recipe with chicken.",
    "Translate 'Good morning' into French.",
    "Give a random fun fact.",
    "Write a slogan for a tech startup.",
    "Describe the feeling of flying.",
    "Generate a workout plan for beginners.",
    "Explain blockchain in simple words.",
    "Write an apology for missing a meeting.",
    "Describe a sunrise in poetic language.",
    "Write an opening line for a thriller novel.",
    "Suggest a romantic date idea.",
    "Explain photosynthesis briefly.",
    "Write a joke about programmers.",
    "Generate a daily affirmation.",
    "Describe a futuristic city.",
    "Write a farewell email to colleagues.",
    "Explain recursion simply.",
    "Write an inspiring message for students.",
    "Describe the taste of dark chocolate.",
    "Generate a random business idea.",
    "Write a motivational text for runners.",
    "Explain the concept of machine learning.",
    "Write a pickup line about books.",
    "Describe the smell of rain.",
    "Generate a two-sentence horror story.",
    "Write a poem about the moon.",
    "Explain Newton's first law.",
    "Write a thank you note for a gift.",
    "Describe a character who is fearless.",
    "Write a creative Instagram caption for nature.",
    "Explain relativity in one sentence.",
    "Write a funny observation about cats.",
    "Describe the feeling of finishing a marathon.",
    "Write a compliment about someone's smile.",
    "Explain the benefits of meditation.",
    "Write a slogan for a coffee shop.",
    "Describe a dragon in detail.",
    "Write a riddle about time.",
    "Explain how a plane flies simply.",
    "Write a line from a villain's monologue.",
    "Describe a snowy mountain peak.",
    "Write a short daily journal entry.",
    "Explain what DNA is in simple terms.",
    "Write a limerick about programming.",
    "Describe the smell of fresh bread.",
    "Write a tweet about Monday mornings.",
    "Explain the concept of democracy.",
    "Write a short product description for a lamp.",
    "Describe an ancient temple.",
    "Write an idea for a viral TikTok.",
    "Explain black holes simply.",
    "Write a short break-up text.",
    "Describe a rainy city street at night.",
    "Write a morning routine for productivity.",
    "Explain cryptocurrency simply.",
    "Write a pun about cheese.",
    "Describe the taste of fresh strawberries.",
    "Write a to-do list for a busy day.",
    "Explain entropy in simple words.",
    "Write a wedding vow.",
    "Describe a powerful storm at sea.",
    "Write a single line about hope.",
    "Explain the internet in simple terms.",
    "Write a line from an epic battle speech.",
    "Describe a secret underground city.",
    "Write a clever password hint.",
    "Explain neural networks simply.",
    "Write a text to cheer up a friend.",
    "Describe the smell of pine trees.",
    "Write a funny poem about WiFi.",
    "Explain the concept of gravity.",
    "Write a creative product slogan for headphones.",
    "Describe a haunted house interior.",
    "Write a motivational quote for athletes.",
    "Explain the purpose of sleep.",
    "Write a short travel tip for Italy.",
    "Describe a serene lake at dawn.",
    "Write a witty response to 'What's up?'",
    "Explain Boolean logic simply.",
    "Write a short thank you email after an interview.",
    "Describe the feeling of riding a roller coaster.",
    "Write a 5-word horror story.",
    "Explain what an API is.",
    "Write a positive morning affirmation.",
    "Describe a spaceship interior.",
    "Write a note to your future self.",
    "Explain carbon footprint simply.",
    "Write a tweet about dogs.",
    "Describe a quiet library scene.",
    "Write a short poem about spring.",
    "Explain the concept of karma.",
    "Write a product name for a fitness app.",
    "Describe the sound of thunder.",
    "Write a line about courage.",
    "Explain the greenhouse effect simply.",
    "Write a romantic text message.",
    "Describe the color blue without using the word blue.",
    "Write a slogan for an eco-friendly brand.",
    "Explain a neural network like a story.",
    "Write a single sentence plot for a sci-fi film.",
    "Describe a beautiful garden in spring.",
    "Write a poem about silence.",
    "Explain the speed of light simply.",
    "Write a funny text to your boss.",
    "Describe the taste of mint ice cream.",
    "Write a daily gratitude entry.",
    "Explain quantum entanglement simply.",
    "Write a riddle about a river.",
    "Describe a forest in autumn.",
    "Write a marketing slogan for sneakers.",
    "Explain serverless computing simply.",
    "Write a line about perseverance.",
    "Describe a bustling city market.",
    "Write a clever pun about coding.",
    "Explain time dilation simply.",
    "Write an apology text for being late.",
    "Describe a luxury hotel room.",
    "Write a motivational caption for a gym selfie.",
    "Explain deep learning simply.",
    "Write a riddle about fire.",
    "Describe a cozy cabin interior.",
    "Write a short toast for a wedding.",
    "Explain prime numbers simply.",
    "Write a positive text to a friend.",
    "Describe a futuristic robot assistant.",
    "Write a haiku about autumn.",
    "Explain the Turing test simply.",
    "Write a caption for a sunset photo.",
    "Describe a giant ancient tree.",
    "Write a romantic Instagram caption.",
    "Explain what an algorithm is simply.",
    "Write a funny observation about Mondays.",
    "Describe the sound of silence.",
    "Write a product description for a backpack.",
    "Explain the concept of inertia.",
    "Write a good morning text.",
    "Describe a pirate ship deck.",
    "Write a single line about happiness.",
    "Explain the big bang theory simply.",
    "Write a riddle about shadows.",
    "Describe a peaceful mountain village.",
    "Write a positive tweet about life.",
    "Explain cloud computing simply.",
    "Write a short text to invite someone for lunch.",
    "Describe a secret garden at night.",
    "Write a marketing slogan for tea.",
    "Explain the Fibonacci sequence simply.",
    "Write a riddle about stars.",
    "Describe an old abandoned castle.",
    "Write a daily intention statement.",
    "Explain recursion with an example.",
    "Write a pickup line about computers.",
    "Describe a medieval banquet hall.",
    "Write a poetic line about water.",
    "Explain general relativity simply.",
    "Write a riddle about mirrors.",
    "Describe a neon-lit city at night.",
    "Write a short tweet about success.",
    "Explain data encryption simply.",
    "Write a pun about bread.",
    "Describe a quiet snowy forest.",
    "Write a wedding anniversary text.",
    "Explain what a database is simply.",
    "Write a positive text about the weekend.",
    "Describe an alien planet landscape.",
    "Write a motivational caption for students.",
    "Explain the concept of energy conservation.",
    "Write a funny riddle about dogs.",
    "Describe a futuristic transportation system.",
    "Write a note of appreciation to a coworker.",
    "Explain natural selection simply.",
    "Write a pun about coding bugs.",
    "Describe an underwater coral reef.",
    "Write a slogan for a mattress company.",
    "Explain what HTTP is simply.",
    "Write a short farewell text.",
    "Describe a quiet candle-lit dinner.",
    "Write a marketing tagline for a phone case.",
    "Explain why the sky is blue simply.",
    "Write a riddle about the sun.",
    "Describe a historic battlefield.",
    "Write a positive daily reflection.",
    "Explain what RAM is simply.",
    "Write a line about resilience.",
    "Describe a jazz club interior.",
    "Write a pun about pizza.",
    "Explain the concept of evolution simply.",
    "Write a short poem about love.",
    "Describe a peaceful meditation room.",
    "Write a product description for wireless earbuds.",
    "Explain the speed of sound simply.",
    "Write a riddle about ice.",
    "Describe a secret library passage.",
    "Write a motivational quote about progress.",
    "Explain what a GPU is simply.",
    "Write a clever pun about AI.",
    "Describe an enchanted forest at dusk.",
    "Write a wedding proposal line.",
    "Explain Moore’s law simply.",
    "Write a riddle about mountains.",
    "Describe a stormy ocean scene.",
    "Write a thank you text to a mentor.",
    "Explain what a compiler does simply.",
    "Write a positive text to start the week.",
    "Describe a quiet reading nook.",
    "Write a funny observation about meetings.",
    "Explain what binary is simply.",
]


results = remote_parallel_map(do_inference, prompts)

print(results)
